# Generated by Django 4.2.5 on 2023-09-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_grooming_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default='x', max_length=1, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('opening_hours', models.CharField(max_length=150)),
            ],
        ),
    ]
