# Generated by Django 4.2.5 on 2023-09-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_grooming_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name_en', models.CharField(max_length=100)),
                ('service_name_hu', models.CharField(max_length=100)),
                ('price_default', models.IntegerField()),
                ('price_small', models.IntegerField(null=True)),
                ('price_big', models.IntegerField(null=True)),
                ('service_description_en', models.TextField()),
                ('service_description_hu', models.TextField()),
                ('max_duration', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to='services')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='opening_hours',
            new_name='opening_hours_en',
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hours_hu',
            field=models.CharField(default='08:00 - 17:00', max_length=150),
            preserve_default=False,
        ),
    ]
