# Generated by Django 4.2.5 on 2023-10-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_grooming_app', '0003_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='google_maps_url',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2726.2653641484812!2d19.65391067680947!3d46.89749933667435!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4743d09cb06aa0cd%3A0xc162d3291067ef90!2sBennett%20Kft.%20Sz%C3%A9kt%C3%B3i%20kutyaszalon!5e0!3m2!1sen!2ses!4v1696190559457!5m2!1sen!2ses', max_length=500),
            preserve_default=False,
        ),
    ]
