# Generated by Django 4.2.5 on 2023-10-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_grooming_app', '0006_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='opening_hours_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='opening_hours_hu',
        ),
        migrations.AddField(
            model_name='contact',
            name='closing_hour_friday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='closing_hour_monday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='closing_hour_saturday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='closing_hour_sunday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='closing_hour_thursday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='closing_hour_tuesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='closing_hour_wednesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hour_friday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hour_monday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hour_saturday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hour_sunday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hour_thursday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hour_tuesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hour_wednesday',
            field=models.TimeField(null=True),
        ),
    ]
