# Generated by Django 4.2.5 on 2023-10-27 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_grooming_app', '0007_remove_contact_opening_hours_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^(?:0036|\\+36|06)[0-9]{1,10}$')]),
        ),
    ]
