# Generated by Django 4.2.5 on 2024-02-12 22:44

from django.db import migrations, models
from django.utils.text import slugify


def fill_slug_field(apps, schema_editor):
    Service = apps.get_model('dog_grooming_app', 'Service')
    for service in Service.objects.all():
        service.slug = slugify(service.service_name_en)
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dog_grooming_app', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(fill_slug_field),
    ]
